spring:
  application:
    name: servidor-gateway
  cloud: 
   gateway:
     default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
     globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
     routes:
      - id: msalumnos 
        uri: lb://msalumnos
        predicates:
          - Path=/api/alumnos/**
        filters:
          - RewritePath=/api/alumnos/*, /alumno/
      - id: mscursos 
        uri: lb://mscursos
        predicates:
          - Path=/api/cursos/**
        filters:
          - RewritePath=/api/cursos/*, /curso/
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka